server:
  port: 8088

spring:
  mvc:
    view:
      #“/”表示resources/static/
      prefix: /
      suffix: .html
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: i18n/language
  thymeleaf:
    cache: false
    #默认目录是resources/templates/
    #prefix: classpath:/myPage/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password:
